### ISSUE TITLE
Does not build with sbcl 1.4.10 - sb-cover type issue?

### ISSUE THREAD

**Issue by quicklisp** [ahungry/ahungry-fleece#1]
Log is here: http://report.quicklisp.org/2018-07-27/failure-report/ahungry-fleece.html#skeleton

**Comment by ahungry** [comment]
Thanks for the heads up @quicklisp  - can  you send me a link or the command you're using to compile?  Both loading the system with sbcl 1.4.10.13-de031aea7 and compile-file seem to work ok, but I'm probably missing something.

The cover.lisp file itself is from sbcl contrib, but mirrored in my codebase as it's public domain, so it was not a missing dependency for the code coverage code I had added.

**Comment by quicklisp** [comment]
Try `(asdf:load-system "ahungry-fleece")` or `(ql:quickload "ahungry-fleece" :verbose t)`. That's how I get the error.

**Comment by ahungry** [comment]
This should be all fixed up now, successful results with 1.4.10 in repo tag 0.5.2 (or latest master commit).

**Comment by quicklisp** [comment]
Now it doesn't build in old SBCLs like 1.4.5. Is there any way to get it to work in both places?

**Comment by ahungry** [comment]
It depends on some of the internals shipped with sbcl (the sb-cover package) - I shadow / copy the package into it's own namespace, but its own internal depends have switched in a backwards compatibility breaking way. 

I might be able to conditionally load one file or the other based on an SBCL version check, or maybe I will need to just remove the code coverage reporting if version is less than 1.4.10 so users with the latest version can enjoy the code coverage reporting.

**Comment by ahungry** [comment]
Going to close this and finish up the other issue.
